// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: test.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Enum1 int32

const (
	Enum1_ENUM1_OPTION0 Enum1 = 0
	Enum1_ENUM1_OPTION1 Enum1 = 1
	Enum1_ENUM1_OPTION2 Enum1 = 2
	Enum1_ENUM1_OPTION3 Enum1 = 3
	Enum1_ENUM1_OPTION4 Enum1 = 4
	Enum1_ENUM1_OPTION5 Enum1 = 5
	Enum1_ENUM1_OPTION6 Enum1 = 6
)

// Enum value maps for Enum1.
var (
	Enum1_name = map[int32]string{
		0: "ENUM1_OPTION0",
		1: "ENUM1_OPTION1",
		2: "ENUM1_OPTION2",
		3: "ENUM1_OPTION3",
		4: "ENUM1_OPTION4",
		5: "ENUM1_OPTION5",
		6: "ENUM1_OPTION6",
	}
	Enum1_value = map[string]int32{
		"ENUM1_OPTION0": 0,
		"ENUM1_OPTION1": 1,
		"ENUM1_OPTION2": 2,
		"ENUM1_OPTION3": 3,
		"ENUM1_OPTION4": 4,
		"ENUM1_OPTION5": 5,
		"ENUM1_OPTION6": 6,
	}
)

func (x Enum1) Enum() *Enum1 {
	p := new(Enum1)
	*p = x
	return p
}

func (x Enum1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Enum1) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Enum1) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Enum1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Enum1.Descriptor instead.
func (Enum1) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

type Enum2 int32

const (
	Enum2_ENUM2_OPTION0 Enum2 = 0
	Enum2_ENUM2_OPTION1 Enum2 = 1
	Enum2_ENUM2_OPTION2 Enum2 = 2
	Enum2_ENUM2_OPTION3 Enum2 = 3
	Enum2_ENUM2_OPTION4 Enum2 = 4
	Enum2_ENUM2_OPTION5 Enum2 = 5
	Enum2_ENUM2_OPTION6 Enum2 = 6
)

// Enum value maps for Enum2.
var (
	Enum2_name = map[int32]string{
		0: "ENUM2_OPTION0",
		1: "ENUM2_OPTION1",
		2: "ENUM2_OPTION2",
		3: "ENUM2_OPTION3",
		4: "ENUM2_OPTION4",
		5: "ENUM2_OPTION5",
		6: "ENUM2_OPTION6",
	}
	Enum2_value = map[string]int32{
		"ENUM2_OPTION0": 0,
		"ENUM2_OPTION1": 1,
		"ENUM2_OPTION2": 2,
		"ENUM2_OPTION3": 3,
		"ENUM2_OPTION4": 4,
		"ENUM2_OPTION5": 5,
		"ENUM2_OPTION6": 6,
	}
)

func (x Enum2) Enum() *Enum2 {
	p := new(Enum2)
	*p = x
	return p
}

func (x Enum2) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Enum2) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[1].Descriptor()
}

func (Enum2) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[1]
}

func (x Enum2) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Enum2.Descriptor instead.
func (Enum2) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

type MainMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Internal:
	//	*MainMessage_Msg1
	//	*MainMessage_Msg2
	//	*MainMessage_Msg3
	Internal isMainMessage_Internal `protobuf_oneof:"internal"`
}

func (x *MainMessage) Reset() {
	*x = MainMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MainMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainMessage) ProtoMessage() {}

func (x *MainMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainMessage.ProtoReflect.Descriptor instead.
func (*MainMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (m *MainMessage) GetInternal() isMainMessage_Internal {
	if m != nil {
		return m.Internal
	}
	return nil
}

func (x *MainMessage) GetMsg1() *OneOfMessage1 {
	if x, ok := x.GetInternal().(*MainMessage_Msg1); ok {
		return x.Msg1
	}
	return nil
}

func (x *MainMessage) GetMsg2() *OneOfMessage2 {
	if x, ok := x.GetInternal().(*MainMessage_Msg2); ok {
		return x.Msg2
	}
	return nil
}

func (x *MainMessage) GetMsg3() *OneOfMessage3 {
	if x, ok := x.GetInternal().(*MainMessage_Msg3); ok {
		return x.Msg3
	}
	return nil
}

type isMainMessage_Internal interface {
	isMainMessage_Internal()
}

type MainMessage_Msg1 struct {
	Msg1 *OneOfMessage1 `protobuf:"bytes,1,opt,name=msg1,proto3,oneof"`
}

type MainMessage_Msg2 struct {
	Msg2 *OneOfMessage2 `protobuf:"bytes,2,opt,name=msg2,proto3,oneof"`
}

type MainMessage_Msg3 struct {
	Msg3 *OneOfMessage3 `protobuf:"bytes,3,opt,name=msg3,proto3,oneof"`
}

func (*MainMessage_Msg1) isMainMessage_Internal() {}

func (*MainMessage_Msg2) isMainMessage_Internal() {}

func (*MainMessage_Msg3) isMainMessage_Internal() {}

type OneOfMessage1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 []byte          `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2 []byte          `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Msg1   *InternalMsg1   `protobuf:"bytes,3,opt,name=msg1,proto3" json:"msg1,omitempty"`
	Msg2   []*InternalMsg2 `protobuf:"bytes,4,rep,name=msg2,proto3" json:"msg2,omitempty"`
}

func (x *OneOfMessage1) Reset() {
	*x = OneOfMessage1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneOfMessage1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfMessage1) ProtoMessage() {}

func (x *OneOfMessage1) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfMessage1.ProtoReflect.Descriptor instead.
func (*OneOfMessage1) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *OneOfMessage1) GetField1() []byte {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *OneOfMessage1) GetField2() []byte {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *OneOfMessage1) GetMsg1() *InternalMsg1 {
	if x != nil {
		return x.Msg1
	}
	return nil
}

func (x *OneOfMessage1) GetMsg2() []*InternalMsg2 {
	if x != nil {
		return x.Msg2
	}
	return nil
}

type OneOfMessage2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field  []byte         `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Field2 *OneOfMessage1 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3 *OneOfMessage1 `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
}

func (x *OneOfMessage2) Reset() {
	*x = OneOfMessage2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneOfMessage2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfMessage2) ProtoMessage() {}

func (x *OneOfMessage2) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfMessage2.ProtoReflect.Descriptor instead.
func (*OneOfMessage2) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *OneOfMessage2) GetField() []byte {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *OneOfMessage2) GetField2() *OneOfMessage1 {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *OneOfMessage2) GetField3() *OneOfMessage1 {
	if x != nil {
		return x.Field3
	}
	return nil
}

type OneOfMessage3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 []*InternalMsg3 `protobuf:"bytes,1,rep,name=field1,proto3" json:"field1,omitempty"`
	Field2 []*InternalMsg2 `protobuf:"bytes,2,rep,name=field2,proto3" json:"field2,omitempty"`
}

func (x *OneOfMessage3) Reset() {
	*x = OneOfMessage3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneOfMessage3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfMessage3) ProtoMessage() {}

func (x *OneOfMessage3) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfMessage3.ProtoReflect.Descriptor instead.
func (*OneOfMessage3) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *OneOfMessage3) GetField1() []*InternalMsg3 {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *OneOfMessage3) GetField2() []*InternalMsg2 {
	if x != nil {
		return x.Field2
	}
	return nil
}

type InternalMsg1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 Enum1  `protobuf:"varint,1,opt,name=field1,proto3,enum=test.Enum1" json:"field1,omitempty"`
	Field2 Enum1  `protobuf:"varint,2,opt,name=field2,proto3,enum=test.Enum1" json:"field2,omitempty"`
	Field3 Enum1  `protobuf:"varint,3,opt,name=field3,proto3,enum=test.Enum1" json:"field3,omitempty"`
	Field4 Enum2  `protobuf:"varint,4,opt,name=field4,proto3,enum=test.Enum2" json:"field4,omitempty"`
	Field5 []byte `protobuf:"bytes,5,opt,name=field5,proto3" json:"field5,omitempty"`
}

func (x *InternalMsg1) Reset() {
	*x = InternalMsg1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalMsg1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalMsg1) ProtoMessage() {}

func (x *InternalMsg1) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalMsg1.ProtoReflect.Descriptor instead.
func (*InternalMsg1) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *InternalMsg1) GetField1() Enum1 {
	if x != nil {
		return x.Field1
	}
	return Enum1_ENUM1_OPTION0
}

func (x *InternalMsg1) GetField2() Enum1 {
	if x != nil {
		return x.Field2
	}
	return Enum1_ENUM1_OPTION0
}

func (x *InternalMsg1) GetField3() Enum1 {
	if x != nil {
		return x.Field3
	}
	return Enum1_ENUM1_OPTION0
}

func (x *InternalMsg1) GetField4() Enum2 {
	if x != nil {
		return x.Field4
	}
	return Enum2_ENUM2_OPTION0
}

func (x *InternalMsg1) GetField5() []byte {
	if x != nil {
		return x.Field5
	}
	return nil
}

type InternalMsg2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 Enum1  `protobuf:"varint,1,opt,name=field1,proto3,enum=test.Enum1" json:"field1,omitempty"`
	Field2 []byte `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3 []byte `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
}

func (x *InternalMsg2) Reset() {
	*x = InternalMsg2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalMsg2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalMsg2) ProtoMessage() {}

func (x *InternalMsg2) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalMsg2.ProtoReflect.Descriptor instead.
func (*InternalMsg2) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *InternalMsg2) GetField1() Enum1 {
	if x != nil {
		return x.Field1
	}
	return Enum1_ENUM1_OPTION0
}

func (x *InternalMsg2) GetField2() []byte {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *InternalMsg2) GetField3() []byte {
	if x != nil {
		return x.Field3
	}
	return nil
}

type InternalMsg3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to FieldOneOf:
	//	*InternalMsg3_Field1
	//	*InternalMsg3_Field2
	FieldOneOf isInternalMsg3_FieldOneOf `protobuf_oneof:"fieldOneOf"`
}

func (x *InternalMsg3) Reset() {
	*x = InternalMsg3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalMsg3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalMsg3) ProtoMessage() {}

func (x *InternalMsg3) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalMsg3.ProtoReflect.Descriptor instead.
func (*InternalMsg3) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (m *InternalMsg3) GetFieldOneOf() isInternalMsg3_FieldOneOf {
	if m != nil {
		return m.FieldOneOf
	}
	return nil
}

func (x *InternalMsg3) GetField1() *InternalOneOfMessage1 {
	if x, ok := x.GetFieldOneOf().(*InternalMsg3_Field1); ok {
		return x.Field1
	}
	return nil
}

func (x *InternalMsg3) GetField2() *InternalOneOfMessage2 {
	if x, ok := x.GetFieldOneOf().(*InternalMsg3_Field2); ok {
		return x.Field2
	}
	return nil
}

type isInternalMsg3_FieldOneOf interface {
	isInternalMsg3_FieldOneOf()
}

type InternalMsg3_Field1 struct {
	Field1 *InternalOneOfMessage1 `protobuf:"bytes,1,opt,name=field1,proto3,oneof"`
}

type InternalMsg3_Field2 struct {
	Field2 *InternalOneOfMessage2 `protobuf:"bytes,2,opt,name=field2,proto3,oneof"`
}

func (*InternalMsg3_Field1) isInternalMsg3_FieldOneOf() {}

func (*InternalMsg3_Field2) isInternalMsg3_FieldOneOf() {}

type InternalOneOfMessage1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 []byte  `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2 []byte  `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3 Enum1   `protobuf:"varint,3,opt,name=field3,proto3,enum=test.Enum1" json:"field3,omitempty"`
	Field4 []int32 `protobuf:"varint,4,rep,packed,name=field4,proto3" json:"field4,omitempty"`
}

func (x *InternalOneOfMessage1) Reset() {
	*x = InternalOneOfMessage1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalOneOfMessage1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalOneOfMessage1) ProtoMessage() {}

func (x *InternalOneOfMessage1) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalOneOfMessage1.ProtoReflect.Descriptor instead.
func (*InternalOneOfMessage1) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *InternalOneOfMessage1) GetField1() []byte {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *InternalOneOfMessage1) GetField2() []byte {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *InternalOneOfMessage1) GetField3() Enum1 {
	if x != nil {
		return x.Field3
	}
	return Enum1_ENUM1_OPTION0
}

func (x *InternalOneOfMessage1) GetField4() []int32 {
	if x != nil {
		return x.Field4
	}
	return nil
}

type InternalOneOfMessage2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field1 []byte                 `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2 *InternalOneOfMessage1 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3 *InternalOneOfMessage1 `protobuf:"bytes,3,opt,name=field3,proto3" json:"field3,omitempty"`
}

func (x *InternalOneOfMessage2) Reset() {
	*x = InternalOneOfMessage2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalOneOfMessage2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalOneOfMessage2) ProtoMessage() {}

func (x *InternalOneOfMessage2) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalOneOfMessage2.ProtoReflect.Descriptor instead.
func (*InternalOneOfMessage2) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *InternalOneOfMessage2) GetField1() []byte {
	if x != nil {
		return x.Field1
	}
	return nil
}

func (x *InternalOneOfMessage2) GetField2() *InternalOneOfMessage1 {
	if x != nil {
		return x.Field2
	}
	return nil
}

func (x *InternalOneOfMessage2) GetField3() *InternalOneOfMessage1 {
	if x != nil {
		return x.Field3
	}
	return nil
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x65,
	0x73, 0x74, 0x22, 0x9a, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x31, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x31, 0x12, 0x29, 0x0a,
	0x04, 0x6d, 0x73, 0x67, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x48, 0x00, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x32, 0x12, 0x29, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x33,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x6e,
	0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x33, 0x48, 0x00, 0x52, 0x04, 0x6d,
	0x73, 0x67, 0x33, 0x42, 0x0a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x22,
	0x8f, 0x01, 0x0a, 0x0d, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x32, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d,
	0x73, 0x67, 0x31, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x31, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x73, 0x67,
	0x32, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x32, 0x52, 0x04, 0x6d, 0x73, 0x67,
	0x32, 0x22, 0x7f, 0x0a, 0x0d, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x32, 0x12, 0x2b, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x6e, 0x65,
	0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x33, 0x22, 0x67, 0x0a, 0x0d, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x33, 0x12, 0x2a, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x33, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12,
	0x2a, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d,
	0x73, 0x67, 0x32, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x22, 0xba, 0x01, 0x0a, 0x0c,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x31, 0x12, 0x23, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x31, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x31, 0x12, 0x23, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x31, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x12, 0x23, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e,
	0x75, 0x6d, 0x31, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x12, 0x23, 0x0a, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x32, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x34,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x35, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x35, 0x22, 0x63, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x32, 0x12, 0x23, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x31, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x22, 0x8a, 0x01,
	0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x33, 0x12, 0x35,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4f, 0x6e,
	0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x48, 0x00, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x35, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x42, 0x0c, 0x0a, 0x0a,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x22, 0x84, 0x01, 0x0a, 0x15, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x32, 0x12, 0x23, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x31, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x34, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x34, 0x22, 0x99, 0x01, 0x0a, 0x15, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4f, 0x6e,
	0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x31, 0x12, 0x33, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x12, 0x33, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x31, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x2a, 0x8c, 0x01,
	0x0a, 0x05, 0x45, 0x6e, 0x75, 0x6d, 0x31, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55, 0x4d, 0x31,
	0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x30, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e,
	0x55, 0x4d, 0x31, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x31, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x45, 0x4e, 0x55, 0x4d, 0x31, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x32, 0x10, 0x02,
	0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55, 0x4d, 0x31, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e,
	0x33, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55, 0x4d, 0x31, 0x5f, 0x4f, 0x50, 0x54,
	0x49, 0x4f, 0x4e, 0x34, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55, 0x4d, 0x31, 0x5f,
	0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x35, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55,
	0x4d, 0x31, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x36, 0x10, 0x06, 0x2a, 0x8c, 0x01, 0x0a,
	0x05, 0x45, 0x6e, 0x75, 0x6d, 0x32, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55, 0x4d, 0x32, 0x5f,
	0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x30, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55,
	0x4d, 0x32, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x31, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d,
	0x45, 0x4e, 0x55, 0x4d, 0x32, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x32, 0x10, 0x02, 0x12,
	0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55, 0x4d, 0x32, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x33,
	0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55, 0x4d, 0x32, 0x5f, 0x4f, 0x50, 0x54, 0x49,
	0x4f, 0x4e, 0x34, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55, 0x4d, 0x32, 0x5f, 0x4f,
	0x50, 0x54, 0x49, 0x4f, 0x4e, 0x35, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4e, 0x55, 0x4d,
	0x32, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x36, 0x10, 0x06, 0x42, 0x0a, 0x5a, 0x08, 0x63,
	0x6d, 0x64, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_test_proto_goTypes = []interface{}{
	(Enum1)(0),                    // 0: test.Enum1
	(Enum2)(0),                    // 1: test.Enum2
	(*MainMessage)(nil),           // 2: test.MainMessage
	(*OneOfMessage1)(nil),         // 3: test.OneOfMessage1
	(*OneOfMessage2)(nil),         // 4: test.OneOfMessage2
	(*OneOfMessage3)(nil),         // 5: test.OneOfMessage3
	(*InternalMsg1)(nil),          // 6: test.InternalMsg1
	(*InternalMsg2)(nil),          // 7: test.InternalMsg2
	(*InternalMsg3)(nil),          // 8: test.InternalMsg3
	(*InternalOneOfMessage1)(nil), // 9: test.InternalOneOfMessage1
	(*InternalOneOfMessage2)(nil), // 10: test.InternalOneOfMessage2
}
var file_test_proto_depIdxs = []int32{
	3,  // 0: test.MainMessage.msg1:type_name -> test.OneOfMessage1
	4,  // 1: test.MainMessage.msg2:type_name -> test.OneOfMessage2
	5,  // 2: test.MainMessage.msg3:type_name -> test.OneOfMessage3
	6,  // 3: test.OneOfMessage1.msg1:type_name -> test.InternalMsg1
	7,  // 4: test.OneOfMessage1.msg2:type_name -> test.InternalMsg2
	3,  // 5: test.OneOfMessage2.field2:type_name -> test.OneOfMessage1
	3,  // 6: test.OneOfMessage2.field3:type_name -> test.OneOfMessage1
	8,  // 7: test.OneOfMessage3.field1:type_name -> test.InternalMsg3
	7,  // 8: test.OneOfMessage3.field2:type_name -> test.InternalMsg2
	0,  // 9: test.InternalMsg1.field1:type_name -> test.Enum1
	0,  // 10: test.InternalMsg1.field2:type_name -> test.Enum1
	0,  // 11: test.InternalMsg1.field3:type_name -> test.Enum1
	1,  // 12: test.InternalMsg1.field4:type_name -> test.Enum2
	0,  // 13: test.InternalMsg2.field1:type_name -> test.Enum1
	9,  // 14: test.InternalMsg3.field1:type_name -> test.InternalOneOfMessage1
	10, // 15: test.InternalMsg3.field2:type_name -> test.InternalOneOfMessage2
	0,  // 16: test.InternalOneOfMessage1.field3:type_name -> test.Enum1
	9,  // 17: test.InternalOneOfMessage2.field2:type_name -> test.InternalOneOfMessage1
	9,  // 18: test.InternalOneOfMessage2.field3:type_name -> test.InternalOneOfMessage1
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MainMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneOfMessage1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneOfMessage2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneOfMessage3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalMsg1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalMsg2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalMsg3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalOneOfMessage1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalOneOfMessage2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_test_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*MainMessage_Msg1)(nil),
		(*MainMessage_Msg2)(nil),
		(*MainMessage_Msg3)(nil),
	}
	file_test_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*InternalMsg3_Field1)(nil),
		(*InternalMsg3_Field2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
